version: "3.4"

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - mssqlserver

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=msSQL@123
    ports:
      - "1433:1433"
